server:
  port: 8001
spring:
   application:
    name: microservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      #com.mysql.cj.jdbc.Driver             # mysql驱动包
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=UTC           # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
   activemq:
     broker-url: tcp://192.168.0.105:61616
     user: admin
     password: admin
   jms:
     pub-sub-domain: false                                   #false=queque, true =topic
   redis:
     host: 192.168.3.58
     port: 6379
#   thymeleaf:
#     prefix:  classpath:/resources/
myqueue: boot-activeMq                                      #定义队列的名字
#######################################一下配置未redis相关配置####################################################